services:
  worker:
    image: h-watanabe/yuyutan-worker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yuyutan-worker
    volumes:
      - type: bind
        source: ..
        target: /workspaces/yuyutan
    working_dir: /workspaces/yuyutan
    environment:
      - REDIS_HOST: redis
    command: /bin/sh -c "poetry install && poetry run python yuyutan/main.py"
    restart: always
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./datas/redis:/data"
