services:
  app:
    image: h-watanabe/yuyutan-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yuyutan-app
    volumes:
      - type: bind
        source: ..
        target: /workspaces/yuyutan
    working_dir: /workspaces/yuyutan
    depends_on:
      - redis
    environment:
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
    command: >
      /bin/sh -c "poetry install &&
      poetry run python workers/periodic_toot.py"
    restart: always
  redis:
    image: "redis:latest"
    container_name: yuyutan-redis
    ports:
      - "6379:6379"
    volumes:
      - "./datas/redis:/data"
  worker:
    image: h-watanabe/yuyutan-app
    container_name: yuyutan-worker
    depends_on:
      - redis
    command: >
      /bin/sh -c "poetry install &&
      rq worker --url redis:6379 --with-scheduler"
