services:
  worker:
    image: h-watanabe/mastodon-bot-worker
    build:
      context: mastodon-bot
      dockerfile: Dockerfile
    container_name: yuyutan-worker
    environment:
      MYSQL_USERNAME: mastodon_bot
      MYSQL_PASSWORD: mastodon_bot
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: mastodon_bot
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - type: bind
        source: ..
        target: /workspaces/yuyutan
    working_dir: /workspaces/yuyutan
    depends_on:
      - redis
    networks:
      - yuyutan-network
    command: >
      /bin/sh -c "bash docker/entrypoint.sh && sleep infinity"
    restart: always
  mysql:
    image: mysql:8.0
    container_name: yuyutan-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mastodon_bot
      MYSQL_PASSWORD: mastodon_bot
      MYSQL_DATABASE: mastodon_bot
      TZ: "Asia/Tokyo"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - type: volume
        source: yuyutan-mysql-data
        target: /var/lib/mysql
        volume:
          nocopy: true
    restart: always
    networks:
      - yuyutan-network
  redis:
    image: "redis:latest"
    container_name: yuyutan-redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - yuyutan-network
  rq-dashboard:
    image: h-watanabe/rq-dashboard
    build:
      context: rq-dashboard
      dockerfile: Dockerfile
    container_name: yuyutan-rq-dashboard
    depends_on:
      - redis
    ports:
      - "9181:9181"
    environment:
      RQ_DASHBOARD_REDIS_URL: redis://redis:6379
    command: rq-dashboard
    restart: always
    networks:
      - yuyutan-network

volumes:
  yuyutan-mysql-data:
    name: yuyutan-mysql-data

networks:
  yuyutan-network:
    name: yuyutan-network
