services:
  worker:
    image: h-watanabe/yuyutan-worker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yuyutan-worker
    volumes:
      - type: bind
        source: ..
        target: /workspaces/yuyutan
    working_dir: /workspaces/yuyutan
    depends_on:
      - redis
    environment:
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
    networks:
      - yuyutan-network
    command: >
      /bin/sh -c "bash entrypoint.sh && sleep infinity"
    restart: always
  redis:
    image: "redis:latest"
    container_name: yuyutan-redis
    ports:
      - "6379:6379"
    volumes:
      - "./datas/redis:/data"
    networks:
      - yuyutan-network
    restart: always

networks:
  yuyutan-network:
    name: yuyutan-network
